In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly as ply
import seaborn as sns
import plotly.graph_objects as go

In [ ]:
#Annual_birth_rate = pd.read_csv("/content/drive/MyDrive/Indian census/dataset-1/Annual-birth-rate-death-rate.csv")
Annual_birth_rate = pd.read_csv('/content/drive/MyDrive/Indian census/dataset-1/updated_Annual-birth-rate-death-rate.csv')

In [ ]:
Annual_birth_rate.head()

Unnamed: 0 Birth rate Unnamed: 2 Unnamed: 3  Unnamed: 4 Death rate  \
0       Year      Total      Rural      Urban         NaN      Total   
1       1971       36.9       38.9       30.1         NaN       14.9   
2       1972       36.6       38.4       30.5         NaN       16.9   
3       1973       34.6       35.9       28.9         NaN       15.5   
4       1974       34.5       35.9       28.4         NaN       14.5   

  Unnamed: 6 Unnamed: 7  Unnamed: 8 Natural growth rate Unnamed: 10  \
0      Rural      Urban         NaN               Total       Rural   
1       16.4        9.7         NaN                  22        22.5   
2       18.9       10.3         NaN                19.7        19.5   
3         17        9.6         NaN                19.1        18.9   
4       15.9        9.2         NaN                  20          20   

  Unnamed: 11  Unnamed: 12 Infant mortality rate Unnamed: 14 Unnamed: 15  \
0       Urban          NaN                 Total       Rural       Urban   
1        20.4          NaN                   129         138          82   
2        20.2          NaN                   139         150          85   
3        19.3          NaN                   134         143          89   
4        19.2          NaN                   126         136          74   

   Unnamed: 16 Total fertility rate Unnamed: 18 Unnamed: 19  
0          NaN                Total       Rural       Urban  
1          NaN                  5.2         5.4         4.1  
2          NaN                  5.2         5.4         4.3  
3          NaN                  4.9         5.2         3.7  
4          NaN                  4.9         5.2         3.7

In [ ]:
header = Annual_birth_rate.iloc[0]
Annual_birth_rate = Annual_birth_rate.iloc[1:,:]
Annual_birth_rate.columns = header 

In [ ]:
Annual_birth_rate = Annual_birth_rate.iloc[:-3,:]

In [ ]:
Annual_birth_rate

0   Year Total Rural Urban  NaN Total Rural Urban  NaN Total Rural Urban  NaN  \
1   1971  36.9  38.9  30.1  NaN  14.9  16.4   9.7  NaN    22  22.5  20.4  NaN   
2   1972  36.6  38.4  30.5  NaN  16.9  18.9  10.3  NaN  19.7  19.5  20.2  NaN   
3   1973  34.6  35.9  28.9  NaN  15.5    17   9.6  NaN  19.1  18.9  19.3  NaN   
4   1974  34.5  35.9  28.4  NaN  14.5  15.9   9.2  NaN    20    20  19.2  NaN   
5   1975  35.2  36.7  28.5  NaN  15.9  17.3  10.2  NaN  19.3  19.4  18.3  NaN   
6   1976  34.4  35.8  28.4  NaN    15  16.3   9.5  NaN  19.4  19.5  18.9  NaN   
7   1977    33  34.3  27.8  NaN  14.7    16   9.4  NaN  18.3  18.3  18.4  NaN   
8   1978  33.3  34.7  27.8  NaN  14.2  15.3   9.4  NaN  19.1  19.4  18.4  NaN   
9   1979  33.1  34.3  28.3  NaN  12.8  13.9   8.4  NaN  20.3  20.4  19.9  NaN   
10  1980  33.3  34.6  28.1  NaN  12.4  13.5     8  NaN  20.9  21.1  20.1  NaN   
11  1981  33.9  35.6    27  NaN  12.5  13.7   7.8  NaN  21.4  21.9  19.2  NaN   
12  1982  33.8  35.5  27.6  NaN  11.9  13.1   7.4  NaN  21.9  22.4  20.2  NaN   
13  1983  33.7  35.3  28.3  NaN  11.9  13.1   7.9  NaN  21.8  22.2  20.4  NaN   
14  1984  33.9  35.3  29.4  NaN  12.6  13.8   8.6  NaN  21.3  21.5  20.8  NaN   
15  1985  32.9  34.3  28.1  NaN  11.8    13   7.8  NaN  21.1  21.3  20.3  NaN   
16  1986  32.6  34.2  27.1  NaN  11.1  12.2   7.6  NaN  21.5    22  19.5  NaN   
17  1987  32.2  33.7  27.4  NaN  10.9    12   7.4  NaN  21.3  21.7    20  NaN   
18  1988  31.5  33.1  26.3  NaN    11    12   7.7  NaN  20.5  21.1  18.6  NaN   
19  1989  30.6  32.2  25.2  NaN  10.3  11.1   7.2  NaN  20.3  21.1    18  NaN   
20  1990  30.2  31.7  24.7  NaN   9.7  10.5   6.8  NaN  20.5  21.2  17.9  NaN   
21  1991  29.5  30.9  24.3  NaN   9.8  10.6   7.1  NaN  19.7  20.3  17.2  NaN   
22  1992  29.2  30.9  23.1  NaN  10.1  10.9     7  NaN  19.1    20  16.1  NaN   
23  1993  28.7  30.4  23.7  NaN   9.3  10.6   5.8  NaN  19.4  19.8  17.9  NaN   
24  1994  28.7  30.5  23.1  NaN   9.3  10.1   6.7  NaN  19.4  20.4  16.4  NaN   
25  1995  28.3    30  22.7  NaN     9   9.8   6.6  NaN  19.3  20.2  16.1  NaN   
26  1996  27.5  29.3  21.6  NaN     9   9.7   6.5  NaN  18.5  19.6  15.1  NaN   
27  1997  27.2  28.9  21.5  NaN   8.9   9.6   6.5  NaN  18.3  19.3    15  NaN   
28  1998  26.5    28  21.1  NaN     9   9.7   6.6  NaN  17.5  18.3  14.5  NaN   
29  1999    26  27.5  20.8  NaN   8.6   9.4   6.3  NaN  17.4  18.1  14.5  NaN   
30  2000  25.8  27.6  20.7  NaN   8.5   9.3   6.3  NaN  17.3  18.3  14.4  NaN   
31  2001  25.4  27.1  20.3  NaN   8.4   9.1   6.3  NaN    17    18    14  NaN   
32  2002    25  26.6    20  NaN   8.1   8.7   6.1  NaN  16.9  17.9  13.9  NaN   
33  2003  24.8  26.4  19.8  NaN     8   8.7     6  NaN  16.8  17.7  13.8  NaN   
34  2004  24.1  25.9    19  NaN   7.5   8.2   5.8  NaN  16.6  17.7  13.2  NaN   
35  2005  23.8  25.6  19.1  NaN   7.6   8.1     6  NaN  16.2  17.5  13.1  NaN   
36  2006  23.5  25.2  18.8  NaN   7.5   8.1     6  NaN    16  17.2  12.8  NaN   
37  2007  23.1  24.7  18.6  NaN   7.4     8     6  NaN  15.7  16.8  12.7  NaN   
38  2008  22.8  24.4  18.5  NaN   7.4     8   5.9  NaN  15.4  16.5  12.6  NaN   
39  2009  22.5  24.1  18.3  NaN   7.3   7.8   5.8  NaN  15.2  16.3  12.5  NaN   
40  2010  22.1  23.7    18  NaN   7.2   7.7   5.8  NaN  14.9  15.9  12.2  NaN   
41  2011  21.8  23.3  17.6  NaN   7.1   7.6   5.7  NaN  14.7  15.7  11.9  NaN   
42  2012  21.6  23.1  17.4  NaN     7   7.6   5.6  NaN  14.5  15.5  11.8  NaN   
43  2013  21.4  22.9  17.3  NaN     7   7.5   5.6  NaN  14.4  15.4  11.7  NaN   

0  Total Rural Urban  NaN Total Rural Urban  
1    129   138    82  NaN   5.2   5.4   4.1  
2    139   150    85  NaN   5.2   5.4   4.3  
3    134   143    89  NaN   4.9   5.2   3.7  
4    126   136    74  NaN   4.9   5.2   3.7  
5    140   151    84  NaN   4.9   5.2   3.7  
6    129   139    80  NaN   4.7     5   3.6  
7    130   140    81  NaN   4.5   4.8   3.4  
8    127   137    74  NaN   4.5   4.8   3.4  
9    120   130    72 

In [ ]:
Annual_birth_rate.columns.unique()
Annual_birth_rate = pd.DataFrame(Annual_birth_rate.iloc[:-1,:4])

In [ ]:
#Annual_birth_rate.explode('Year')
Annual_birth_rate.explode('Total')
Annual_birth_rate['Total']=Annual_birth_rate.Total.astype(float)
Annual_birth_rate.explode('Rural')
Annual_birth_rate['Rural']=Annual_birth_rate.Rural.astype(float)
Annual_birth_rate.explode('Urban')
Annual_birth_rate['Urban']=Annual_birth_rate.Urban.astype(float)


In [ ]:
import plotly.graph_objects as go
fig = go.Figure(layout_yaxis_range=[0,40])
fig.add_trace(go.Bar(y=Annual_birth_rate.iloc[:,:3]['Total'],x=Annual_birth_rate['Year'],name= "Total ",marker_color = 'rgb(0,0,255)'))
#fig.add_trace(go.Bar(y=Annual_birth_rate.iloc[:,:3]['Rural'],x=Annual_birth_rate['Year'],name= "Rural ",marker_color = 'rgb(255,00,0)'))
#fig.add_trace(go.Bar(y=Annual_birth_rate.iloc[:,:4]['Urban'],x=Annual_birth_rate['Year'],name= "Urban",marker_color = 'rgb(255,255,00)'))

fig.update_layout(
    title="BIRTH RATE ESTIMATION PER YEAR ",
  
)
fig.update_layout( font= dict(
        size=25,
        color="RebeccaPurple"
    ))
fig.show()

PREDICTION USING MACHINE LEARNING 


In [ ]:
year = list(Annual_birth_rate['Year'])
years =[]
for string in year:
    new_string = string.replace("*", "")
    years.append(new_string)


In [ ]:
for i in range(0, len(years)):
    years[i] = int(years[i])


In [ ]:
birth_rate = list(Annual_birth_rate.iloc[:,:3]['Total'])
for i in range(0, len(birth_rate)):
    birth_rate[i] = int(birth_rate[i])



In [ ]:
years = pd.DataFrame(years)
Birth_rate = pd.DataFrame(birth_rate)

In [ ]:
years = years.rename(columns = {0:"Year"})

In [ ]:
Birth_rate = Birth_rate.rename(columns ={0:"BR"})

In [ ]:
print(years)
print(Birth_rate)

    Year
0   1971
1   1972
2   1973
3   1974
4   1975
5   1976
6   1977
7   1978
8   1979
9   1980
10  1981
11  1982
12  1983
13  1984
14  1985
15  1986
16  1987
17  1988
18  1989
19  1990
20  1991
21  1992
22  1993
23  1994
24  1995
25  1996
26  1997
27  1998
28  1999
29  2000
30  2001
31  2002
32  2003
33  2004
34  2005
35  2006
36  2007
37  2008
38  2009
39  2010
40  2011
41  2012
    BR
0   36
1   36
2   34
3   34
4   35
5   34
6   33
7   33
8   33
9   33
10  33
11  33
12  33
13  33
14  32
15  32
16  32
17  31
18  30
19  30
20  29
21  29
22  28
23  28
24  28
25  27
26  27
27  26
28  26
29  25
30  25
31  25
32  24
33  24
34  23
35  23
36  23
37  22
38  22
39  22
40  21
41  21


In [ ]:
#Fitting the Linear Regression model
from sklearn.linear_model import LinearRegression
slr = LinearRegression()  
slr.fit(years,Birth_rate)

LinearRegression()

In [ ]:
#new_years = pd.DataFrame(np.array([2020,2021,2022,2023,2025]).reshape(-1,1))
new_years = np.array([2013,2014,2015,2016,2017,2018,2019,2020,2021,2022]).reshape(-1,1)

In [ ]:
#Intercept and Coefficient
print("Intercept: ", slr.intercept_)
print("Coefficient: ", slr.coef_)

Intercept:  [771.39888718]
Coefficient:  [[-0.37290333]]


In [ ]:
y_pred_slr= slr.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



In [ ]:
y_pred_slr

array([[20.74448316],
       [20.37157983],
       [19.9986765 ],
       [19.62577317],
       [19.25286984],
       [18.87996651],
       [18.50706318],
       [18.13415985],
       [17.76125652],
       [17.38835319]])

In [ ]:
a = slr.intercept_ + (slr.coef_[0])*2020

In [ ]:
a

array([18.13415985])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
slrmse = mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_pred_slr)
slrrmse = math.sqrt(mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_pred_slr))
print(slrmse)
print(slrrmse)

226.3202529552615
15.043944062487785


In [ ]:
 #Fitting the Polynomial regression to the dataset  
from sklearn.preprocessing import PolynomialFeatures  
poly_regs= PolynomialFeatures(degree= 2)  
x_poly= poly_regs.fit_transform(years)  
lin_reg_2 =LinearRegression()  
lin_reg_2.fit(x_poly, birth_rate)  

LinearRegression()

In [ ]:
new_years_x_poly= poly_regs.fit_transform(new_years) 

In [ ]:
y_poly_pred = lin_reg_2.predict(new_years_x_poly)

In [ ]:
y_poly_pred

array([19.83188153, 19.33163844, 18.82560718, 18.31378774, 17.79618014,
       17.27278436, 16.74360042, 16.2086283 , 15.66786801, 15.12131955])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
dmse = mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_poly_pred)
drmse  = math.sqrt(mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_poly_pred))
print(dmse)
print(drmse)

275.76036502576665
16.60603399447823


In [ ]:
# Fitting Decision Tree Regression to the dataset
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(years,Birth_rate)

DecisionTreeRegressor()

In [ ]:
y_pred_DTregressor= regressor.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names



In [ ]:
y_pred_DTregressor

array([21., 21., 21., 21., 21., 21., 21., 21., 21., 21.])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
dmse = mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_pred_DTregressor)
drmse  = math.sqrt(mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_pred_DTregressor))
print(dmse)
print(drmse)

172.9
13.149144458861192


In [ ]:
from sklearn.svm import SVR
SVM_regressor = SVR(kernel = 'rbf')
SVM_regressor.fit(years, Birth_rate)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



SVR()

In [ ]:
y_pred_SVM = SVM_regressor.predict(new_years)
y_pred_SVM

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but SVR was fitted with feature names



array([23.182462  , 23.44821538, 23.76227814, 24.1139931 , 24.49193723,
       24.88455471, 25.28075323, 25.67041906, 26.04481861, 26.39686785])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
smse =mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_pred_SVM)
srmse=math.sqrt(mean_squared_error(Birth_rate.iloc[:len(new_years),:], y_pred_SVM))
print(smse)
print(srmse)

92.31768144988443
9.608209065683596


In [ ]:
from sklearn.linear_model import Ridge
rng = np.random.RandomState(0)

rdg = Ridge(alpha = 0.2)
rdg.fit(years, Birth_rate)
#rdg.score(X,y)
ridgepredictor = rdg.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but Ridge was fitted with feature names



In [ ]:
from sklearn.metrics import mean_squared_error
import math
rmse = mean_squared_error(Birth_rate.iloc[:len(new_years),:], ridgepredictor)
rrmse =math.sqrt(mean_squared_error(Birth_rate.iloc[:len(new_years),:], ridgepredictor))
print(rmse)
print(math.sqrt(mean_squared_error(Birth_rate.iloc[:len(new_years),:], ridgepredictor)))

226.31079919514212
15.043629854365006


In [ ]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=1.0)
lasso.fit(years,Birth_rate)
LassoPredicter = lasso.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but Lasso was fitted with feature names



In [ ]:
from sklearn.metrics import mean_squared_error
import math
lmse = mean_squared_error(Birth_rate.iloc[:len(new_years),:], LassoPredicter)
lrmse = math.sqrt(mean_squared_error(Birth_rate.iloc[:len(new_years),:], LassoPredicter))
print(lmse)
print(lrmse)

221.02785301543608
14.867005516089515


In [ ]:
Results_df = pd.DataFrame({'New Year':new_years.reshape(-1),'Linear Regression':y_pred_slr.reshape(-1), 'Decision Tree Regression':y_pred_DTregressor.reshape(-1),'Polynomial Regression':y_poly_pred.reshape(-1),'SVM Regression':y_pred_SVM.reshape(-1),'Ridge Regression':ridgepredictor.reshape(-1),"Lasso Regression":LassoPredicter.reshape(-1)})

In [ ]:
Results_df

New Year  Linear Regression  Decision Tree Regression  \
0      2013          20.744483                      21.0   
1      2014          20.371580                      21.0   
2      2015          19.998676                      21.0   
3      2016          19.625773                      21.0   
4      2017          19.252870                      21.0   
5      2018          18.879967                      21.0   
6      2019          18.507063                      21.0   
7      2020          18.134160                      21.0   
8      2021          17.761257                      21.0   
9      2022          17.388353                      21.0   

   Polynomial Regression  SVM Regression  Ridge Regression  Lasso Regression  
0              19.831882       23.182462         20.744743         20.890825  
1              19.331638       23.448215         20.371852         20.524728  
2              18.825607       23.762278         19.998961         20.158631  
3              18.313788       24.113993         19.626069         19.792534  
4              17.796180       24.491937         19.253178         19.426438  
5              17.272784       24.884555         18.880287         19.060341  
6              16.743600       25.280753         18.507396         18.694244  
7              16.208628       25.670419         18.134504         18.328147  
8              15.667868       26.044819         17.761613         17.962051  
9              15.121320       26.396868         17.388722         17.595954

In [ ]:
import plotly.express as px 
fig = px.line(Results_df, x='New Year', y=Results_df.columns[1:])
fig.update_layout( 
    xaxis_title='Year',
    yaxis_title='Birth Rate',
    font= dict(
        size=25,
        color="RebeccaPurple"
    ))
fig.show()
