In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly as ply
import seaborn as sns
import plotly.graph_objects as go

In [ ]:
#Annual_birth_rate = pd.read_csv("/content/drive/MyDrive/Indian census/dataset-1/Annual-birth-rate-death-rate.csv")
Annual_birth_rate = pd.read_csv('/content/drive/MyDrive/Indian census/dataset-1/updated_Annual-birth-rate-death-rate.csv')

In [ ]:
Annual_birth_rate.head()

Unnamed: 0 Birth rate Unnamed: 2 Unnamed: 3  Unnamed: 4 Death rate  \
0       Year      Total      Rural      Urban         NaN      Total   
1       1971       36.9       38.9       30.1         NaN       14.9   
2       1972       36.6       38.4       30.5         NaN       16.9   
3       1973       34.6       35.9       28.9         NaN       15.5   
4       1974       34.5       35.9       28.4         NaN       14.5   

  Unnamed: 6 Unnamed: 7  Unnamed: 8 Natural growth rate Unnamed: 10  \
0      Rural      Urban         NaN               Total       Rural   
1       16.4        9.7         NaN                  22        22.5   
2       18.9       10.3         NaN                19.7        19.5   
3         17        9.6         NaN                19.1        18.9   
4       15.9        9.2         NaN                  20          20   

  Unnamed: 11  Unnamed: 12 Infant mortality rate Unnamed: 14 Unnamed: 15  \
0       Urban          NaN                 Total       Rural       Urban   
1        20.4          NaN                   129         138          82   
2        20.2          NaN                   139         150          85   
3        19.3          NaN                   134         143          89   
4        19.2          NaN                   126         136          74   

   Unnamed: 16 Total fertility rate Unnamed: 18 Unnamed: 19  
0          NaN                Total       Rural       Urban  
1          NaN                  5.2         5.4         4.1  
2          NaN                  5.2         5.4         4.3  
3          NaN                  4.9         5.2         3.7  
4          NaN                  4.9         5.2         3.7

In [ ]:
header = Annual_birth_rate.iloc[0]
Annual_birth_rate = Annual_birth_rate.iloc[1:,:]
Annual_birth_rate.columns = header 

In [ ]:
Annual_Death_rate = pd.DataFrame(Annual_birth_rate.iloc[:-1,5:8])


In [ ]:
Annual_Death_rate = Annual_Death_rate.fillna(0) 
Annual_Death_rate

0  Total Rural Urban
1   14.9  16.4   9.7
2   16.9  18.9  10.3
3   15.5    17   9.6
4   14.5  15.9   9.2
5   15.9  17.3  10.2
6     15  16.3   9.5
7   14.7    16   9.4
8   14.2  15.3   9.4
9   12.8  13.9   8.4
10  12.4  13.5     8
11  12.5  13.7   7.8
12  11.9  13.1   7.4
13  11.9  13.1   7.9
14  12.6  13.8   8.6
15  11.8    13   7.8
16  11.1  12.2   7.6
17  10.9    12   7.4
18    11    12   7.7
19  10.3  11.1   7.2
20   9.7  10.5   6.8
21   9.8  10.6   7.1
22  10.1  10.9     7
23   9.3  10.6   5.8
24   9.3  10.1   6.7
25     9   9.8   6.6
26     9   9.7   6.5
27   8.9   9.6   6.5
28     9   9.7   6.6
29   8.6   9.4   6.3
30   8.5   9.3   6.3
31   8.4   9.1   6.3
32   8.1   8.7   6.1
33     8   8.7     6
34   7.5   8.2   5.8
35   7.6   8.1     6
36   7.5   8.1     6
37   7.4     8     6
38   7.4     8   5.9
39   7.3   7.8   5.8
40   7.2   7.7   5.8
41   7.1   7.6   5.7
42     7   7.6   5.6
43     7   7.5   5.6
44     0     0     0
45     0     0     0

In [ ]:
Annual_Death_rate.explode('Total')
Annual_Death_rate['Total']=Annual_Death_rate.Total.astype(float)
Annual_Death_rate.explode('Rural')
Annual_Death_rate['Rural']=Annual_Death_rate.Rural.astype(float)
Annual_Death_rate.explode('Urban')
Annual_Death_rate['Urban']=Annual_Death_rate.Urban.astype(float)

In [ ]:
Annual_birth_rate = Annual_birth_rate.iloc[:-3,:]

In [ ]:
import plotly.graph_objects as go
fig = go.Figure(layout_yaxis_range=[0,25])
fig.add_trace(go.Bar(y=Annual_Death_rate['Total'],x=Annual_birth_rate['Year'],name= "Total ",marker_color = 'rgb(0,0,255)'))
fig.update_layout(
    title="DEATH RATE ESTIMATION PER YEAR ",
  
)
fig.update_layout( font= dict(
        size=25,
        color="RebeccaPurple"
    ))
fig.show()

In [ ]:
year = list(Annual_birth_rate['Year'])
years =[]
for string in year:
    new_string = string.replace("*", "")
    years.append(new_string)

In [ ]:
for i in range(0, len(years)):
    years[i] = int(years[i])


In [ ]:
Death_rate = list(Annual_Death_rate.iloc[:,:3]['Total'])
for i in range(0, len(Death_rate)):
    Death_rate[i] = int(Death_rate[i])



In [ ]:
years = pd.DataFrame(years)
Death_rate = pd.DataFrame(Death_rate)

In [ ]:
years = years.rename(columns = {0:"Year"})
Death_rate = Death_rate.rename(columns ={0:"DR"})

In [ ]:
Death_rate = Death_rate.iloc[:-2,:]

In [ ]:
#Fitting the Linear Regression model
from sklearn.linear_model import LinearRegression
slr = LinearRegression()  
slr.fit(years,Death_rate)

LinearRegression()

In [ ]:
#new_years = pd.DataFrame(np.array([2020,2021,2022,2023,2025]).reshape(-1,1))
new_years = np.array([2013,2014,2015,2016,2017,2018,2019,2020,2021,2022]).reshape(-1,1)

In [ ]:
#Intercept and Coefficient
print("Intercept: ", slr.intercept_)
print("Coefficient: ", slr.coef_)

Intercept:  [426.35185744]
Coefficient:  [[-0.2090003]]


In [ ]:
y_pred_slr= slr.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



In [ ]:
a = slr.intercept_ + (slr.coef_[0])*2020
a

array([4.17124736])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
slrmse = mean_squared_error(Death_rate.iloc[:len(new_years),:], y_pred_slr)
slrrmse = math.sqrt(mean_squared_error(Death_rate.iloc[:len(new_years),:], y_pred_slr))
print(slrmse)
print(slrrmse)


89.26204232507662
9.447859139777467


In [ ]:
 #Fitting the Polynomial regression to the dataset  
from sklearn.preprocessing import PolynomialFeatures  
poly_regs= PolynomialFeatures(degree= 2)  
x_poly= poly_regs.fit_transform(years)  
lin_reg_2 =LinearRegression()  
lin_reg_2.fit(x_poly, Death_rate)  

LinearRegression()

In [ ]:
new_years_x_poly= poly_regs.fit_transform(new_years) 

In [ ]:
y_poly_pred = lin_reg_2.predict(new_years_x_poly)

In [ ]:
y_poly_pred

array([[6.8435518 ],
       [6.81573616],
       [6.79634773],
       [6.78538648],
       [6.78285243],
       [6.78874557],
       [6.80306591],
       [6.82581344],
       [6.85698816],
       [6.89659008]])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
pmse = mean_squared_error(Death_rate.iloc[:len(new_years),:], y_poly_pred)
prmse =math.sqrt(mean_squared_error(Death_rate.iloc[:len(new_years),:], y_poly_pred)) 
print(pmse)
print(prmse)

54.5622402213743
7.38662576697739


In [ ]:
# Fitting Decision Tree Regression to the dataset
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(years,Death_rate)

DecisionTreeRegressor()

In [ ]:
y_pred_DTregressor= regressor.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names



In [ ]:
y_pred_DTregressor

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
dmse = mean_squared_error(Death_rate.iloc[:len(new_years),:], y_pred_DTregressor)
drmse  = math.sqrt(mean_squared_error(Death_rate.iloc[:len(new_years),:], y_pred_DTregressor))
print(dmse)
print(drmse)

51.9
7.20416546173115


In [ ]:
from sklearn.svm import SVR
SVM_regressor = SVR(kernel = 'rbf')
SVM_regressor.fit(years, Death_rate)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



SVR()

In [ ]:
y_pred_SVM = SVM_regressor.predict(new_years)
y_pred_SVM


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but SVR was fitted with feature names



array([7.1971123 , 7.32255102, 7.47273659, 7.64323807, 7.82915231,
       8.0253575 , 8.22676112, 8.42852638, 8.62626396, 8.81618003])

In [ ]:
from sklearn.metrics import mean_squared_error
import math
smse =mean_squared_error(Death_rate.iloc[:len(new_years),:], y_pred_SVM)
srmse=math.sqrt(mean_squared_error(Death_rate.iloc[:len(new_years),:], y_pred_SVM))
print(smse)
print(srmse)

40.460262305691906
6.3608381763484525


In [ ]:
from sklearn.linear_model import Ridge
rng = np.random.RandomState(0)
y = Death_rate
X = years
rdg = Ridge(alpha = 0.2)
rdg.fit(X, y)
rdg.score(X,y)
ridgepredictor = rdg.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but Ridge was fitted with feature names



In [ ]:
from sklearn.metrics import mean_squared_error
import math
rmse = mean_squared_error(Death_rate.iloc[:len(new_years),:], ridgepredictor)
rrmse =math.sqrt(mean_squared_error(Death_rate.iloc[:len(new_years),:], ridgepredictor))
print(rmse)
print(math.sqrt(mean_squared_error(Death_rate.iloc[:len(new_years),:], ridgepredictor)))

89.25902473720285
9.447699441515


In [ ]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=1.0)
lasso.fit(years,Death_rate)
LassoPredicter = lasso.predict(new_years)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning:

X does not have valid feature names, but Lasso was fitted with feature names



In [ ]:
from sklearn.metrics import mean_squared_error
import math
lmse = mean_squared_error(Death_rate.iloc[:len(new_years),:], LassoPredicter)
lrmse = math.sqrt(mean_squared_error(Death_rate.iloc[:len(new_years),:], LassoPredicter))
print(lmse)
print(lrmse)

86.18547494048276
9.28361324810996


In [ ]:
Results_df = pd.DataFrame({'New Year':new_years.reshape(-1),'Linear Regression':y_pred_slr.reshape(-1), 'Decision Tree Regression':y_pred_DTregressor.reshape(-1),'Polynomial Regression':y_poly_pred.reshape(-1),'SVM Regression':y_pred_SVM.reshape(-1),'Ridge Regression':ridgepredictor.reshape(-1),"Lasso Regression":LassoPredicter.reshape(-1)})

In [ ]:
Results_df

New Year  Linear Regression  Decision Tree Regression  \
0      2013           5.634249                       7.0   
1      2014           5.425249                       7.0   
2      2015           5.216249                       7.0   
3      2016           5.007249                       7.0   
4      2017           4.798248                       7.0   
5      2018           4.589248                       7.0   
6      2019           4.380248                       7.0   
7      2020           4.171247                       7.0   
8      2021           3.962247                       7.0   
9      2022           3.753247                       7.0   

   Polynomial Regression  SVM Regression  Ridge Regression  Lasso Regression  
0               6.843552        7.197112          5.634382          5.770613  
1               6.815736        7.322551          5.425388          5.568106  
2               6.796348        7.472737          5.216394          5.365600  
3               6.785386        7.643238          5.007400          5.163093  
4               6.782852        7.829152          4.798406          4.960586  
5               6.788746        8.025357          4.589412          4.758079  
6               6.803066        8.226761          4.380418          4.555572  
7               6.825813        8.428526          4.171424          4.353066  
8               6.856988        8.626264          3.962430          4.150559  
9               6.896590        8.816180          3.753436          3.948052

In [ ]:
import plotly.express as px 
fig = px.line(Results_df, x='New Year', y=Results_df.columns[1:])
fig.update_layout( 
    xaxis_title='Year',
    yaxis_title='Death Rate',
    font= dict(
        size=25,
        color="RebeccaPurple"
    ))
fig.show()